### PR TITLE
Create pt_br.json

### PR DESCRIPTION
**Pull request by Brun333rp**
Brazilian portuguese translations

### CODE REVIEW

**Comment by Brun333rp** [comment]
before the translations are done, I need to know what a "Blubber Jelly" is supposed to be

**Comment by VakyPanda** [comment]
Blubber jellies aren't implemented in the mod, so you do not need to translate them over.

**Comment by Brun333rp** [comment]
any idea of when the update containing them will be released?

**Comment by N1nn1** [comment]
> any idea of when the update containing them will be released?

it won't, we stopped developing the mod

**Comment by Brun333rp** [comment]
> it won't, we stopped developing the mod

I see. so, no translations for the mod then?

**Comment by Coda1552** [comment]
> > it won't, we stopped developing the mod
> 
> I see. so, no translations for the mod then?

Ninni's reply is inaccurate. We won't be adding new content to the mod, but we will be fixing bugs and adding stuff such as translations.

**Comment by Brun333rp** [comment]
the most recent update includes Mudskipper fishes, and seems like they would be abscent in the "Blubber Jelly" update. May I still add translations for them and remove the "Blubber Jelly" strings?

**Pull request merged**
